"""
Lab: Package Split
Lesson: python-modules

The code below is a monolith: classification logic and batch processing
tangled together in one file. Do NOT edit this file.

Instead, create two NEW files in this same folder:

    classification.py  -- containing classify_demand(), moved out of here
    main.py             -- containing run_batch(readings), which must
                            IMPORT classify_demand from classification.py
                            (not redefine it)

This file is left as a reference for what the monolith looked like
before the split.
"""


def classify_demand(reading_kw, safe_limit_kw=5000, warning_kw=4500):
    if reading_kw >= safe_limit_kw:
        return "OVERLOAD"
    elif reading_kw > warning_kw:
        return "WARNING"
    return "NORMAL"


def run_batch(readings):
    return [classify_demand(r) for r in readings]


if __name__ == "__main__":
    print(run_batch([4821, 4790, 5100]))
